### PR TITLE
Adding Docker

### PR DESCRIPTION
**Pull request by luizperes**
This PR adds instructions of how to install Brain using Docker

### CODE REVIEW

**Comment by rafaelcn** [comment]
I did a rebase and merge, is that ok @luizperes?

**Comment by rafaelcn** [comment]
Also, it closes #33.

**Comment by rafaelcn** [comment]
Oh, actually not, my bad.

**Comment by luizperes** [comment]
strange... the `dev` branch is not even with the `master`

**Comment by rafaelcn** [comment]
Yep, that's weird ._.

**Pull request merged**
