### PR TITLE
Adds a cleaning instruction fo clang++ builds

### PR DESCRIPTION
**Pull request by rafaelcn**
When compiling with clang++ it generates .dwo files, the Makefile now removes it in the end of the build.

Signed-off-by: Rafael Campos Nunes <rafaelnunes@engineer.com>

### CODE REVIEW

**Comment by luizperes** [comment]
Do you think that you are able to check this one here as well: https://github.com/brain-labs/brain/issues/54?

**Comment by rafaelcn** [comment]
Sure, will get my hands on it :-)

**Comment by luizperes** [comment]
THANKS! Should we put that on the same PR? What do you think?

**Comment by rafaelcn** [comment]
Well, that doesn't reflect the title of the same PR but it's okay for me. We'll need to change the title and the commit message though,

**Comment by luizperes** [comment]
I dont think that I get those files xD `.dwo`

**Comment by rafaelcn** [comment]
Well, I figure out that we need those `*.dwo` files when debugging Brain compiled with clang. So I just removed those commands and told the Makefile to move those `*.dwo` files when building a debug version of Brain.

**Comment by rafaelcn** [comment]
Things are more than meets the eye. Those are files are [DWARF](http://wiki.dwarfstd.org) files, used to make the final Brain executable, they are **dw**arf **o**bjects, hence the `.dwo` extension. I think #54 is somehow related to the linking process of Brain and with what you said inside that issue. [Here's](https://stackoverflow.com/questions/31495312/how-to-dump-dwarf-information-into-a-file-while-llvm-compiles#31508471) a related issue, quite close to what we are experiencing.

**Comment by luizperes** [comment]
Interesting, any news on #54?

**Comment by luizperes** [comment]
It's been approved already xD

**Pull request merged**
