### PR TITLE
Updated documentation and some identation

### PR DESCRIPTION
**Pull request by rafaelcn**
It looks like documentation is complete if not by some very few
items, I would say it is complete. :v: 
Also, the indentation is some places were fixed.

Signed-off-by: Rafael Campos Nunes <rafaelnunes@engineer.com>

### CODE REVIEW

**Comment by luizperes** [comment]
Can you add the doc files? :)

**Comment by rafaelcn** [comment]
Sure, on my way to do it :dancer:

**Comment by rafaelcn** [comment]
Way to go, documentation done! :+1:

**Comment by luizperes** [comment]
Thanks!

**Pull request merged**
