### PR TITLE
Bump dev into master

### PR DESCRIPTION
**Pull request by luizperes**

### CODE REVIEW

**Comment by rafaelcn** [comment]
You may merge whenever you want @luizperes.

**Comment by ryukinix** [comment]
image

I WANT MERGE THIS.

**Comment by luizperes** [comment]
You will need to aprove the PR first @ryukinix. I can't aprove it, because I was the one who created the PR.

**Comment by rafaelcn** [comment]
Actually @luizperes I think that one approve is enough to merge.

**Pull request merged**
