### PR TITLE
Fixes a memory leak

### PR DESCRIPTION
**Pull request by rafaelcn**
As described in ecff41e _instance was leaking after execution of the program.

### CODE REVIEW

**Comment by rafaelcn** [comment]
Need on you @luizperes on this.

**Comment by luizperes** [comment]
Hi @rafaelcn, do you think you can check if the other Singleton are fine? :) thanks!

**Comment by rafaelcn** [comment]
Sure!

**Comment by luizperes** [comment]
Please inform me when you think we are good to go @rafaelcn! :)

**Comment by rafaelcn** [comment]
I'm low on time right now. So I'll verify that whenever I can, probably in the weekend

**Comment by luizperes** [comment]
thanks!

**Comment by rafaelcn** [comment]
Check the newest changes @luizperes :-)

**Comment by luizperes** [comment]
You may merge whenever you want @rafaelcn

**Pull request merged**
